apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    acme.com/requests: "4"
  name: requests-4
  namespace: apps
spec:
  serviceName: test
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - args:
        - sleep
        - "3600"
        image: busybox
        name: request-4
        resources:
          requests:
              cpu: "4"
      restartPolicy: Always
  
