apiVersion: batch/v1
kind: Job
metadata:
  labels:
    acme.com/requests: "4"
  name: requests-4
  namespace: apps
spec:
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - args:
        - sleep
        - "3600"
        image: busybox
        name: request-4
        resources:
          requests:
              cpu: "4"
      restartPolicy: Never
  
